### ISSUE TITLE
directory not empty error

### ISSUE THREAD

**Issue by ankur7721** [DevashishPrasad/CascadeTabNet#28]
```
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2'
Traceback (most recent call last):
  File "C:\Users\ABC\AppData\Local\Continuum\anaconda3\envs\python3env\lib\site-packages\mmcv\utils\config.py", line 92, in _file2dict
    osp.join(temp_config_dir, temp_config_name))
  File "C:\Users\ABC\AppData\Local\Continuum\anaconda3\envs\python3env\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ABC\\AppData\\Local\\Temp\\tmp2x0tbf44\\tmpg99tl4cb.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 17, in <module>
    model = init_detector(config_fname, os.path.join(checkpoint_path, epoch))
  File "C:\Users\ABC\AppData\Local\Continuum\anaconda3\envs\python3env\lib\site-packages\mmdet-2.0.0+a9bedfb-py3.6-win-amd64.egg\mmdet\apis\inference.py", line 28, in init_detector
    config = mmcv.Config.fromfile(config)
  File "C:\Users\ABC\AppData\Local\Continuum\anaconda3\envs\python3env\lib\site-packages\mmcv\utils\config.py", line 165, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "C:\Users\ABC\AppData\Local\Continuum\anaconda3\envs\python3env\lib\site-packages\mmcv\utils\config.py", line 105, in _file2dict
    temp_config_file.close()
  File "C:\Users\ABC\AppData\Local\Continuum\anaconda3\envs\python3env\lib\tempfile.py", line 809, in __exit__
    self.cleanup()
  File "C:\Users\ABC\AppData\Local\Continuum\anaconda3\envs\python3env\lib\tempfile.py", line 813, in cleanup
    _shutil.rmtree(self.name)
  File "C:\Users\ABC\AppData\Local\Continuum\anaconda3\envs\python3env\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\ABC\AppData\Local\Continuum\anaconda3\envs\python3env\lib\shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\ABC\AppData\Local\Continuum\anaconda3\envs\python3env\lib\shutil.py", line 391, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] The directory is not empty: 'C:\\Users\\ABC\\AppData\\Local\\Temp\\tmp2x0tbf44'


```

On running `main.py` with this [config ](https://github.com/open-mmlab/mmdetection/blob/master/configs/hrnet/faster_rcnn_hrnetv2p_w32_1x_coco.py) file and this [model ](https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmdetection/v2.0/hrnet/faster_rcnn_hrnetv2p_w32_1x_coco/faster_rcnn_hrnetv2p_w32_1x_coco_20200130-6e286425.pth) file, I am again and again getting this error

Other Details:
CUDA version : 9.2
OS : Windows
Main.py config
```
image_path = 'Examples\\cTDaR_t10120.jpg'
xmlPath = 'Examples'


config_fname = "Examples\\faster_rcnn_hrnetv2p_w32_1x_coco.py" 
checkpoint_path = "C:\\Users\\ABC\\Music\\table-structure-rec\\CascadeTabNet\\Table Structure Recognition\\Examples\\"
epoch = 'faster_rcnn_hrnetv2p_w32_1x_coco_20200130-6e286425.pth'

**Comment by kshitijkapadni** [comment]
PyTorch = 1.4.0
Torchvision = 0.5.0
Cuda = 10.0

These are the recommended versions to be used. The issue is probably due to the CUDA version mismatch or it is unable to find the CUDA runtime as per given below:

No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2'

**Comment by ankur7721** [comment]
Thanks for your reply @kshitijkapadni. I am able to resolve some part of the error[Cuda error] but main error still persists.

here's the updated error message
```

---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\envs\vision\lib\site-packages\mmcv\utils\config.py in _file2dict(filename)
     91                 shutil.copyfile(filename,
---> 92                                 osp.join(temp_config_dir, temp_config_name))
     93                 temp_module_name = osp.splitext(temp_config_name)[0]

~\AppData\Local\Continuum\anaconda3\envs\vision\lib\shutil.py in copyfile(src, dst, follow_symlinks)
    120         with open(src, 'rb') as fsrc:
--> 121             with open(dst, 'wb') as fdst:
    122                 copyfileobj(fsrc, fdst)

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ABC\\AppData\\Local\\Temp\\tmpk364o8er\\tmpdvxuk41c.py'

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-4-1bf7d6119595> in <module>
      1 # build the model from a config file and a checkpoint file
----> 2 model = init_detector(config_file, checkpoint_path, device='cuda:0')

c:\users\ABC\music\table-structure-rec\cascadetabnet\mmdetection\mmdet\apis\inference.py in init_detector(config, checkpoint, device)
     27     """
     28     if isinstance(config, str):
---> 29         config = mmcv.Config.fromfile(config)
     30     elif not isinstance(config, mmcv.Config):
     31         raise TypeError('config must be a filename or Config object, '

~\AppData\Local\Continuum\anaconda3\envs\vision\lib\site-packages\mmcv\utils\config.py in fromfile(filename)
    163     @staticmethod
    164     def fromfile(filename):
--> 165         cfg_dict, cfg_text = Config._file2dict(filename)
    166         return Config(cfg_dict, cfg_text=cfg_text, filename=filename)
    167 

~\AppData\Local\Continuum\anaconda3\envs\vision\lib\site-packages\mmcv\utils\config.py in _file2dict(filename)
    103                 del sys.modules[temp_module_name]
    104                 # close temp file
--> 105                 temp_config_file.close()
    106         elif filename.endswith(('.yml', '.yaml', '.json')):
    107             import mmcv

~\AppData\Local\Continuum\anaconda3\envs\vision\lib\tempfile.py in __exit__(self, exc, value, tb)
    807 
    808     def __exit__(self, exc, value, tb):
--> 809         self.cleanup()
    810 
    811     def cleanup(self):

~\AppData\Local\Continuum\anaconda3\envs\vision\lib\tempfile.py in cleanup(self)
    811     def cleanup(self):
    812         if self._finalizer.detach():
--> 813             _shutil.rmtree(self.name)

~\AppData\Local\Continuum\anaconda3\envs\vision\lib\shutil.py in rmtree(path, ignore_errors, onerror)
    492             os.close(fd)
    493     else:
--> 494         return _rmtree_unsafe(path, onerror)
    495 
    496 # Allow introspection of whether or not the hardening against symlink

~\AppData\Local\Continuum\anaconda3\envs\vision\lib\shutil.py in _rmtree_unsafe(path, onerror)
    391         os.rmdir(path)
    392     except OSError:
--> 393         onerror(os.rmdir, path, sys.exc_info())
    394 
    395 # Version using fd-based APIs to protect against races

~\AppData\Local\Continuum\anaconda3\envs\vision\lib\shutil.py in _rmtree_unsafe(path, onerror)
    389                 onerror(os.unlink, fullname, sys.exc_info())
    390     try:
--> 391         os.rmdir(path)
    392     except OSError:
    393         onerror(os.rmdir, path, sys.exc_info())

OSError: [WinError 145] The directory is not empty: 'C:\\Users\\ABC\\AppData\\Local\\Temp\\tmpk364o8er'

```

**Comment by ankur7721** [comment]
To add further into my findings, Error is coming into this [function](https://github.com/open-mmlab/mmcv/blob/c63e4d57c3c38d8d016ff5035320d6ff9277e524/mmcv/utils/config.py#L83)  of line 91.

**Comment by AyanGadpal** [comment]
Hey @ankur7721 , I think you should try [this](https://github.com/DevashishPrasad/CascadeTabNet/issues/37#issuecomment-637997809)
