### ISSUE TITLE
name 'etree' is not defined

### ISSUE THREAD

**Issue by weinixuehao** [DevashishPrasad/CascadeTabNet#33]
[Table status] : Processing table with lines
<PIL.Image.Image image mode=RGB size=812x349 at 0x7F9D02BBA860>
<PIL.Image.Image image mode=RGB size=1224x1584 at 0x7F9D012A60B8>
Traceback (most recent call last):
  File "CascadeTabNet/Table Structure Recognition/main.py", line 53, in <module>
    root.append(borderless(res,cv2.imread(i),res_cell))
  File "/content/gdrive/My Drive/CascadeTabNet/CascadeTabNet/Table Structure Recognition/Functions/blessFunc.py", line 365, in borderless
    tableXML = etree.Element("table")
NameError: name 'etree' is not defined

**Comment by kshitijkapadni** [comment]
from lxml import etree might be missing.

I have updated it
Thanks for pointing the bug.
